from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        base_model = models.load_model('model.keras')
        self.model = Sequential(base_model.layers[:-1]) # remove the last layer of the loaded model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        self._randomize_layers(self.model)
        for layer in self.model.layers:
            layer.trainable = False
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        self.model.add(layers.Dense(64, activation='relu', name = 'random_dense'))
        self.model.add(layers.Dense(categories_count, activation='softmax', name = 'random_output'))
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=Adam(learning_rate=0.001),
            loss='categorical_crossentropy',
            metrics=['accuracy']
        )

    @staticmethod
    def _randomize_layers(model):
        # Your code goes here

        # you can write a function here to set the weights to a random value
        # use this function in _define_model to randomize the weights of your loaded model

        for layer in model.layers:
            if hasattr(layer, 'kernel_initializer'):
                new_weights = layer.kernel_initializer(layer.kernel.shape)
                layer.kernel.assign(new_weights)
            if hasattr(layer, 'bias_initializer'):
                new_bias = layer.bias_initializer(layer.bias.shape)
                layer.bias.assign(new_bias)
