from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        base_model = models.load_model('model.keras')

        self.model = Sequential(base_model.layers[:-1]) # remove the last layer of the loaded model
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        for layer in self.model.layers:
            layer.trainable = False
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer
        self.model.add(layers.Dense(64, activation='relu', name = 'transfered_dense'))
        self.model.add(layers.Dense(categories_count, activation='softmax', name = 'transfered_output'))
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=Adam(learning_rate=0.001),
            loss='categorical_crossentropy',
            metrics=['accuracy']
        )
